upstream django {
    server web:8000;
}

upstream flower {
    server web:5555;
}

server {
    listen 81;

    location /flower_app/ {
        proxy_pass http://flower;
        rewrite ^/flower_app/(.*)$ /$1 break;
    }

    location /upload_excel/ {
        client_max_body_size 50M;
        proxy_pass http://django;  # адрес gunicorn — подставить свой
        proxy_read_timeout 120s;
    }

    location / {
        proxy_pass http://django;
    }

    location /static/ {
        alias /static/;
    }
}