# Generated by Django 5.0.3 on 2024-03-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_date', models.DateField(verbose_name='Дата обработка')),
                ('case_id', models.CharField(max_length=32, verbose_name='ID в CaseBook')),
                ('is_success', models.BooleanField(default=False, verbose_name='Успешно выполнено?')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка, если не успешно')),
            ],
            options={
                'verbose_name': 'Обработанное дело',
                'verbose_name_plural': 'Обработанные дела',
                'db_table': 'processed_case',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.JSONField()),
                ('filter_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopword', models.CharField(max_length=128, verbose_name='Стоп-слово')),
            ],
            options={
                'verbose_name': 'Стоп-слов',
                'verbose_name_plural': 'Стоп-слова   ',
                'db_table': 'stopwords',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_expire', models.IntegerField()),
                ('iteration_interval', models.IntegerField()),
                ('filter_id', models.CharField(max_length=64)),
                ('last_execution', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
