# Generated by Django 5.0.3 on 2024-04-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='bitrix_lead_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID лида в Б24'),
        ),
    ]
