# Generated by Django 5.0.3 on 2024-04-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0002_case_bitrix_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='bitrix_lead_id',
            field=models.CharField(blank=True, null=True, verbose_name='ID лида в Б24'),
        ),
    ]
