# Generated by Django 5.0.3 on 2024-04-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0003_alter_case_bitrix_lead_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('type', models.CharField(choices=[('inn', 'Организация'), ('email', 'эл.почта'), ('phone', 'Номер телефона')], max_length=32, verbose_name='Тип')),
            ],
        ),
    ]
