# Generated by Django 5.0.3 on 2025-01-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0004_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='scan_p',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='scan_r',
            field=models.BooleanField(default=True),
        )
    ]
