# Generated by Django 5.0.3 on 2025-01-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0005_alter_blacklist_options_tasks_cash_tasks_to_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='contacts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
