# Generated by Django 5.0.3 on 2025-01-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0006_tasks_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='emails',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
