# Generated by Django 5.0.3 on 2025-02-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0006_tasks_scan_p_tasks_scan_r_alter_case_case_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='ignore_other_tasks_processed',
            field=models.BooleanField(default=False, verbose_name='Игнорировать кейсы обработки других подборок'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='regex_p',
            field=models.CharField(default=None, null=True, verbose_name='Регулярное выражение для истцов (в разработке)'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='regex_r',
            field=models.CharField(default=None, null=True, verbose_name='Регулярное выражение для ответчиков (в разработке)'),
        ),
    ]
