# Generated by Django 5.0.3 on 2025-02-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0007_tasks_ignore_other_tasks_processed_tasks_regex_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='regex_p',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Регулярное выражение для истцов (в разработке)'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='regex_r',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Регулярное выражение для ответчиков (в разработке)'),
        ),
    ]
