# Generated by Django 5.0.3 on 2025-02-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0008_alter_tasks_regex_p_alter_tasks_regex_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='scan_or',
            field=models.BooleanField(default=False, verbose_name='Применять стоп-слова на поле `OtherRespondent`'),
        ),
    ]
