# Generated by Django 5.2 on 2025-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0009_tasks_scan_or'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='b24_collection',
            field=models.IntegerField(blank=True, null=True, verbose_name='Тип прав (id из битрикса)'),
        ),
    ]
