# Generated by Django 5.0.3 on 2025-05-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0010_tasks_b24_collection_alter_blacklist_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoDealB24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b24_id', models.IntegerField(blank=True, null=True)),
                ('case_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instance_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_record_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_casebook', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='type',
            field=models.CharField(choices=[('inn', 'Организация'), ('email', 'эл.почта'), ('phone', 'Номер телефона'), ('email_mask', 'Домен эл.почты')], max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='value',
            field=models.CharField(help_text='В случае с `Доменом электронной почты` - работает концепция как со стоп-словами - поиск подстроки в строке. ПРИМЕР - блокирует все электронки на определенном домене, например, в случае с mvideo: "<something>@mvideo.ru", при этом вместоsomething - может быть любой текст, то есть ключевое здесь домен`mvideo.ru` или `@mvideo.ru`', max_length=255, verbose_name='Значение'),
        ),
    ]
