name: Deploy on production server
on:
  pull_request:
      branches:
        - main
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop production server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/docker/BitrixCasebookDjango/
            docker compose down web 

      - name: Backup DB
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: sh /home/docker/BitrixCasebookDjango/backups/scheduled_pg_dump.sh

      - name: Copy environment variables to remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm /home/docker/BitrixCasebookDjango/.env
            echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > /home/docker/BitrixCasebookDjango/.env
            echo "BITRIX_CALLBACK=${{ secrets.BITRIX_CALLBACK }}" >> /home/docker/BitrixCasebookDjango/.env
            echo "CASEBOOK_LOGIN=${{ secrets.CASEBOOK_LOGIN }}" >> /home/docker/BitrixCasebookDjango/.env
            echo "CASEBOOK_PASSWORD=${{ secrets.CASEBOOK_PASSWORD }}" >> /home/docker/BitrixCasebookDjango/.env
            echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> /home/docker/BitrixCasebookDjango/.env
            echo "EXPORT_BASE_API_KEY=${{ secrets.EXPORT_BASE_API_KEY }}" >> /home/docker/BitrixCasebookDjango/.env

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/docker/BitrixCasebookDjango/
            git pull origin main
            docker compose restart web
